import { Card, Suit } from "../types/GameTypes";

export const allCards = [
  {
    id: 1,
    name: Card.CARD_A,
    suit: Suit.CLUB,
    image: require("../images/aceofclubs.jpg"),
  },
  {
    id: 2,
    name: Card.CARD_A,
    suit: Suit.DIAMOND,
    image: require("../images/aceofdiamonds.jpg"),
  },
  {
    id: 3,
    name: Card.CARD_A,
    suit: Suit.HEART,
    image: require("../images/aceofhearts.jpg"),
  },
  {
    id: 4,
    name: Card.CARD_A,
    suit: Suit.SPADES,
    image: require("../images/aceofspades.jpg"),
  },
  {
    id: 5,
    name: Card.CARD_K,
    suit: Suit.CLUB,
    image: require("../images/kingofclubs.jpg"),
  },
  {
    id: 6,
    name: Card.CARD_K,
    suit: Suit.DIAMOND,
    image: require("../images/kingofdiamonds.jpg"),
  },
  {
    id: 7,
    name: Card.CARD_K,
    suit: Suit.HEART,
    image: require("../images/kingofhearts.jpg"),
  },
  {
    id: 8,
    name: Card.CARD_K,
    suit: Suit.SPADES,
    image: require("../images/kingofspades.jpg"),
  },
  {
    id: 9,
    name: Card.CARD_Q,
    suit: Suit.CLUB,
    image: require("../images/queenofclubs.jpg"),
  },
  {
    id: 10,
    name: Card.CARD_Q,
    suit: Suit.DIAMOND,
    image: require("../images/queenofdiamonds.jpg"),
  },
  {
    id: 11,
    name: Card.CARD_Q,
    suit: Suit.HEART,
    image: require("../images/queenofhearts.jpg"),
  },
  {
    id: 12,
    name: Card.CARD_Q,
    suit: Suit.SPADES,
    image: require("../images/queenofspades.jpg"),
  },
  {
    id: 13,
    name: Card.CARD_J,
    suit: Suit.CLUB,
    image: require("../images/jackofclubs.jpg"),
  },
  {
    id: 14,
    name: Card.CARD_J,
    suit: Suit.DIAMOND,
    image: require("../images/jackofdiamonds.jpg"),
  },
  {
    id: 15,
    name: Card.CARD_J,
    suit: Suit.HEART,
    image: require("../images/jackofhearts.jpg"),
  },
  {
    id: 16,
    name: Card.CARD_J,
    suit: Suit.SPADES,
    image: require("../images/jackofspades.jpg"),
  },
  {
    id: 17,
    name: Card.CARD_10,
    suit: Suit.CLUB,
    image: require("../images/tenofclubs.jpg"),
  },
  {
    id: 18,
    name: Card.CARD_10,
    suit: Suit.DIAMOND,
    image: require("../images/tenofdiamonds.jpg"),
  },
  {
    id: 19,
    name: Card.CARD_10,
    suit: Suit.HEART,
    image: require("../images/tenofhearts.jpg"),
  },
  {
    id: 20,
    name: Card.CARD_10,
    suit: Suit.SPADES,
    image: require("../images/tenofspades.jpg"),
  },
  {
    id: 21,
    name: Card.CARD_9,
    suit: Suit.CLUB,
    image: require("../images/nineofclubs.jpg"),
  },
  {
    id: 22,
    name: Card.CARD_9,
    suit: Suit.DIAMOND,
    image: require("../images/nineofdiamonds.jpg"),
  },
  {
    id: 23,
    name: Card.CARD_9,
    suit: Suit.HEART,
    image: require("../images/nineofhearts.jpg"),
  },
  {
    id: 24,
    name: Card.CARD_9,
    suit: Suit.SPADES,
    image: require("../images/nineofspades.jpg"),
  },
  {
    id: 25,
    name: Card.CARD_8,
    suit: Suit.CLUB,
    image: require("../images/eightofclubs.jpg"),
  },
  {
    id: 26,
    name: Card.CARD_8,
    suit: Suit.DIAMOND,
    image: require("../images/eightofdiamonds.jpg"),
  },
  {
    id: 27,
    name: Card.CARD_8,
    suit: Suit.HEART,
    image: require("../images/eightofhearts.jpg"),
  },
  {
    id: 28,
    name: Card.CARD_8,
    suit: Suit.SPADES,
    image: require("../images/eightofspades.jpg"),
  },
  {
    id: 29,
    name: Card.CARD_7,
    suit: Suit.CLUB,
    image: require("../images/sevenofclubs.jpg"),
  },
  {
    id: 30,
    name: Card.CARD_7,
    suit: Suit.DIAMOND,
    image: require("../images/sevenofdiamonds.jpg"),
  },
  {
    id: 31,
    name: Card.CARD_7,
    suit: Suit.HEART,
    image: require("../images/sevenofhearts.jpg"),
  },
  {
    id: 32,
    name: Card.CARD_7,
    suit: Suit.SPADES,
    image: require("../images/sevenofspades.jpg"),
  },
  {
    id: 33,
    name: Card.CARD_6,
    suit: Suit.CLUB,
    image: require("../images/sixofclubs.jpg"),
  },
  {
    id: 34,
    name: Card.CARD_6,
    suit: Suit.DIAMOND,
    image: require("../images/sixofdiamonds.jpg"),
  },
  {
    id: 35,
    name: Card.CARD_6,
    suit: Suit.HEART,
    image: require("../images/sixofhearts.jpg"),
  },
  {
    id: 36,
    name: Card.CARD_6,
    suit: Suit.SPADES,
    image: require("../images/sixofspades.jpg"),
  },
];
